# 01 — Exploration : chargement et inspection

**Source :** [Online Retail sur Kaggle](https://www.kaggle.com/datasets/carrie1/ecommerce-data), données d'origine UCI, licence CC BY 4.0

**Questions métier :**
1. Quels pays, hors Royaume-Uni, rapportent le plus de chiffre d'affaires, et quel continent domine ?
2. Comment le chiffre d'affaires évolue-t-il mois par mois ? Y a-t-il un pic avant Noël ?
3. Quels jours de la semaine et quelles heures concentrent le plus de commandes ?
4. Quels produits rapportent le plus de chiffre d'affaires ?

**Objectif de ce notebook :** charger les données avec les bons types et faire l'état des lieux avant tout nettoyage.

In [58]:
import pandas as pd

In [59]:
vente = pd.read_csv("../data/raw/online_retail.csv", parse_dates=["InvoiceDate"], dtype={"InvoiceNo": "str", "StockCode": "str", "CustomerID": "str"}, encoding="latin-1")
vente.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047,United Kingdom

In [60]:
vente.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID                str
Country                   str
dtype: object

- InvoiceNo et StockCode : Restent en str. Ce sont des identifiants, et ils contiennent des lettres
- Description : Reste str. Contient le nom des produits
- Quantity : Reste int64. Cette colonne sera utilisée afin de faire des calculs comme des sommes et des moyennes
- InvoiceDate : str ==> date. Afin d'effectuer une analyse par période
- UnitPrice : Reste float64. Un prix se calcule avec des décimales
- CustomerID : float64 ==> str. Il s'agit d'un identifiant client, il ne sert pas pour les calculs
- Country : Reste str. Va servir pour grouper

In [61]:
vente["InvoiceDate"].min(), vente["InvoiceDate"].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [62]:
vente.shape

(541909, 8)

In [63]:
vente.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  str
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 33.1 MB

In [64]:
vente.describe()

            Quantity                 InvoiceDate      UnitPrice
count  541909.000000                      541909  541909.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114
min    -80995.000000         2010-12-01 08:26:00  -11062.060000
25%         1.000000         2011-03-28 11:34:00       1.250000
50%         3.000000         2011-07-19 17:17:00       2.080000
75%        10.000000         2011-10-19 11:27:00       4.130000
max     80995.000000         2011-12-09 12:50:00   38970.000000
std       218.081158                         NaN      96.759853

In [65]:
vente["StockCode"].value_counts()

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
23609        1
85179a       1
23617        1
90214U       1
47591b       1
Name: count, Length: 4070, dtype: int64

In [66]:
vente["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [67]:
vente.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [68]:
vente.isna().mean().round(3)

InvoiceNo      0.000
StockCode      0.000
Description    0.003
Quantity       0.000
InvoiceDate    0.000
UnitPrice      0.000
CustomerID     0.249
Country        0.000
dtype: float64

In [69]:
vente.duplicated().sum()

np.int64(5268)

In [70]:
vente.duplicated().mean().round(3)

np.float64(0.01)

## Constats de l'inspection

| # | Colonne | Constat | Chiffre | Conséquence pour l'analyse |
|---|---|---|---|---|
| 1 | Description | Lignes vides | 1 454 (0,3 %) | Produit inconnu pour la Q4 |
| 2 | CustomerID | Lignes vides | 135 080 (24,9 %) | Aucune question ne compte les clients : à garder |
| 3 | Quantity | Quantité minimum impossible (négative) | min −80 995 | Fausse les sommes et les moyennes |
| 4 | UnitPrice | Prix minimum impossible (négatif) | min −11 062,06 | Fausse le chiffre d'affaires |
| 5 | StockCode | Code pas toujours écrit de la même manière (ex. 85179a) | 4 070 codes distincts | Ne fausse pas les calculs |
| 6 | Toutes | Doublons | 5 268 (1,0 %) | Ventes comptées deux fois |